/*Assignment agenda:

Use an immediate assertion to test the behavior of the adder for 10 random stimuli generated by TB. Use the design and TB code mentioned in the instructions tab.

*/

`timescale 1ns / 1ps
module tb;
  
  reg [3:0] a, b;
  wire [4:0] s;
  
  adder dut (a, b, s);
  
  initial begin
    for(int i = 0; i < 10; i++) begin
      a = $urandom;
      b = $urandom;
      #10;
      assert (s == a + b) $info("Success at time : %0t",$time()); else $error("Failure at time : %0t",$time());
    end   
  end
  
  
   initial begin
    $dumpfile("dump.vcd"); 
    $dumpvars;
    $assertvacuousoff(0);
    #110;
    $finish();
  end
  
  
endmodule
